config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users
#   root to: 'pages#home'
#     resources :events, only: [:index, :show] do
#       get 'attend', to: "events#attend"
#       resources :attendees, only: [:index, :new, :create]
#     end

#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    root to: 'pages#home'
    resources "contacts", only: [:new, :create]
    get "/about" => "pages#about", as: :about_page


    resources :events, only: [ :show] do
      get 'attend', to: "events#attend"
      resources :attendees, only: [:index, :new, :create]
    end
    resources :attendees, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "New message from NOBODY",
      :to => "c.k.treweek@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendees
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :attendees

   def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email)
      if user
       user.update(user_params)
      else
       user = User.new(user_params)
       user.password = Devise.friendly_token[0,20]  # Fake password for validation
       user.save
      end
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  skip_before_action :authenticate_user!
  def new
    @attendee = Attendee.new
    @event = Event.find(params[:event_id])
  end

  def create
    @attendee = Attendee.new
    @attendee.user = current_user
    @event = Event.find(params[:event_id])
    @user = User.find(params[:user_id])
    @attendee.save
  end

  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy
    redirect_to :back
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end


  def attend
    @event = Event.find(params[:event_id])
    @user = current_user
    attendees = []
    @event.attendees.each do |attendee|
    attendees << attendee.user_id
    end
   if attendees.include?(@user.id)
    # @event_ids = []

    # @user.attendees.each do |attendee|
    # @event_ids << attendee.event_id
    # end
    # if @event_ids.include?(@event.id)
      redirect_to event_path(@event)
    else
      Attendee.create(user_id: @user.id, event_id: @event.id)
      redirect_to event_path(@event)
    end
  end

  def attending?
    @event = Event.find(params[:event_id])
    @user = current_user
    @event_ids = []

    @user.attendees.each do |attendee|
    @event_ids << attendee.event_id
    end
    if @event_ids.include?(@event.id)
      return true
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :show]

  def home
  end

  def about
    # render template: "pages/#{params[:about]}"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendees/new.html.erb
<div class= text-center>
<h4>Will you be attending <%= @event.name %> ?</h4>
</div>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us!</h3>
</div>
<div class="text-center">
  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>
</div>
</div>

app/views/events/index.html.erb
<% @events.each do |event| %>
<ul class="text-center" style="list-style: none">
<li><%= link_to event.name, event_path(event)%></li>
</ul>
<% end %>

app/views/events/show.html.erb
<div class="card text-center">
  <h3>You're offically invited to</h3>
  <h1><%= @event.name %></h1>
  <h5><%= @event.address %></h5>
  <h5><%= @event.start_time %> until <%= @event.end_time %></h5>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal">
    Guest List
  </button>
  <br>


  <div class="text-center">
    <% if user_signed_in? %>
    <% @attending = current_user.attendees.select {|attendee| attendee.event_id == @event.id} %>
    <% if @attending.length > 0 %>
    <h4 class="text-center">You're on the guest list!</h4>
    <% @attendee = @attending[0].id %>
    <%= link_to "Unattend", attendee_path(@attendee), method: :delete %>
    <% else %>
    <%= link_to "Click to attend", event_attend_path(@event), method: :get, class: "btn btn-primary" %>
    <% end %>
    <% else %>
    <%= link_to "RSVP", new_user_session_path  %>
    <% end %>
  </div>
</div>




<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><%=@event.name  %> Guest List</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @event.attendees.each do |attendee| %>
        <% user_id = attendee.user_id %>
        <% user = User.find(user_id) %>
        <%= user.first_name %> <%= user.last_name %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>nobody's popup</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class = "text-center">Meet the team</h1>
<div class="team-members text-center">
  <div class="dom member" >
    <h4>Domingo Henry</h4>
    <img src="/assets/dom.jpg" alt="" class = "avatar-team">
    <div class= "about-bio">
      <p>Domingo was born and raised in a small town in Pennsylvania. Moving around and gaining experience in the business world, Dominic has managed local and corporate businesses until moving to Gainesville, Florida. Spending time as an active community member, planning multiple local events and working in the service industry, drove him to found NOBODY. </p>
    </div>
  </div>

  <div class= "clara member">
    <h4>Clara Leibinger</h4>
    <img src="/assets/clara.jpg" alt="" class="avatar-team">
  </div>
</div>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Nobody's popup party</h1>
    <p>Party for a cause</p>
  <div>
    <div class="row yellow-blocks">
      <div class="col-xs-3 col-lg-3">
      </div>
      <div class="col-xs-3 col-lg-3">
      </div>
      <div class="col-xs-3 col-lg-3">
      </div>

    </div>
  </div>
    <% if Event.count >= 1  %>
    <%= link_to "TONIGHT'S EVENT", event_path(Event.last), class: "btn btn-primary btn-lg"%>

    <% else %>
      <h4>Stay tuned for the next event!</h4>
    <% end %>
    <div>
    <%= link_to "About", about_page_path, class: "btn btn-primary btn-lg"  %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo2.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>